import type {} from '@mui/material/themeCssVarsAugmentation'

export type { Account } from '@lifi/wallet-provider'
export * from './hooks/useAccount.js'
export * from './hooks/useAccountDisconnect.js'
export * from './hooks/useWalletManagementEvents.js'
export * from './icons.js'
export * from './providers/WalletManagementProvider/types.js'
export * from './providers/WalletManagementProvider/WalletManagementProvider.js'
export type { WalletMenuOpenArgs } from './providers/WalletMenuProvider/types.js'
export * from './providers/WalletMenuProvider/WalletMenuContext.js'
export * from './types/events.js'
export * from './types/walletConfig.js'
export * from './types/walletConnector.js'
export * from './utils/getConnectorIcon.js'
export * from './utils/getWalletPriority.js'
export * from './utils/isWalletInstalled.js'
