name: Deploy Widget to Testing Web via SSH

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install
      - name: Build WebApp
        run: yarn build
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8 # easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: 'packages/widget-embedded/build/' # optional, default is
          TARGET: ${{ secrets.REMOTE_TARGET }}/test/web-testing # optional, default is /home/REMOTE_USER/

      # # Purge Cloudflare caches (https://github.com/marketplace/actions/cloudflare-purge-cache)
      # - name: Purge cache
      #   uses: jakejarvis/cloudflare-purge-action@master
      #   env:
      #     CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ONE }}
      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      #     PURGE_URLS: '["https://testing.li.fi/"]'

      # # Notify Rollbar about release
      # - name: Notify deploy to Rollbar
      #   uses: rollbar/github-deploy-action@2.1.1
      #   id: rollbar_deploy
      #   with:
      #     environment: 'testing'
      #     version: ${{ github.sha }}
      #   env:
      #     ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
