
name: Deploy Widget Playground to S3

on:
  push:
    branches: [ "main" ]
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      id-token: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::403372804574:role/github-actions
          role-session-name: github-actions-role-session
          aws-region: us-east-2
      - name: Amazon ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build React App
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn install && yarn build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./packages/widget-playground/dist/ s3://playground.li.fi --delete
